# Generated by Django 5.2 on 2025-12-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0003_remove_vacancy_short_requirements_shortrequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortrequirement",
            name="text_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Требование",
            ),
        ),
        migrations.AddField(
            model_name="shortrequirement",
            name="text_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Требование",
            ),
        ),
        migrations.AddField(
            model_name="shortrequirement",
            name="text_uz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Требование",
            ),
        ),
    ]
