# Generated by Django 5.2 on 2025-12-17 06:02

import colorfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#4CAF50",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#FF5252", "Red"),
                            ("#4CAF50", "Green"),
                            ("#2196F3", "Blue"),
                            ("#FF9800", "Orange"),
                            ("#9C27B0", "Purple"),
                            ("#00BCD4", "Cyan"),
                            ("#FFEB3B", "Yellow"),
                            ("#795548", "Brown"),
                            ("#607D8B", "Gray"),
                        ],
                        verbose_name="Цвет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бейдж",
                "verbose_name_plural": "Бейджи",
            },
        ),
    ]
