# Generated by Django 5.2 on 2025-12-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_badge"),
        ("news", "0002_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                to="common.badge",
                verbose_name="Бейдж",
            ),
        ),
    ]
