default_language_version:
  python: python3.10

exclude: >
  (\.eggs|\.git|\.hg|\.mypy_cache|\.idea|\.pytest_cache|\.tox|\.venv|venv|\.env|env|\.vscode|
  static|media/|.*/templates|.*/migrations)

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.10
        additional_dependencies: []
        args: [--fast]

  - repo: local
    hooks:
      - id: migrations-check
        name: Check for uncreated migrations
        entry: ./manage.py makemigrations --check --dry-run
        language: system
        files: 'models\.py$'
        stages: [pre-commit]
