# Generated by Django 5.2 on 2025-08-02 17:00

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название категории"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Название категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория блога",
                "verbose_name_plural": "Категории блогов",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="Слаг"
                    ),
                ),
                ("content", tinymce.models.HTMLField(verbose_name="Контент")),
                (
                    "content_uz",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "content_ru",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "content_en",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="blog.blogcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
