# Generated by Django 5.2 on 2025-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="course",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="what_will_learn_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Чему вы научитесь"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="what_will_learn_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Чему вы научитесь"
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="name_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="name_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="text_uz",
            field=models.TextField(null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="mentor",
            name="bio_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Биография"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="bio_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Биография"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="position_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="position_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Должность"
            ),
        ),
    ]
