# Generated by Django 5.2 on 2025-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_company_name_ru_company_name_uz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="message_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_en",
            field=models.CharField(
                default="8-12 месяцев",
                max_length=50,
                null=True,
                verbose_name="Продолжительность",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level_en",
            field=models.CharField(
                choices=[
                    ("beginner", "Новички"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                default="beginner",
                max_length=20,
                null=True,
                verbose_name="Уровень",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="what_will_learn_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Чему вы научитесь"
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="message_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="bio_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Биография"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="position_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="position_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Текст отзыва"),
        ),
    ]
