# Generated by Django 5.2 on 2025-05-17 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_company_name_en_contactrequest_message_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseregistration",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="message_en",
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="message_ru",
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="message_uz",
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="name_uz",
        ),
        migrations.RemoveField(
            model_name="courseregistration",
            name="message_en",
        ),
        migrations.RemoveField(
            model_name="courseregistration",
            name="message_ru",
        ),
        migrations.RemoveField(
            model_name="courseregistration",
            name="message_uz",
        ),
        migrations.RemoveField(
            model_name="courseregistration",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="courseregistration",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="courseregistration",
            name="name_uz",
        ),
        migrations.AddField(
            model_name="course",
            name="bitrix_category_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Bitrix категория ID"
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="birth_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата рождения"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="last_name",
            field=models.CharField(
                default="test", max_length=255, verbose_name="Фамилия"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Отчество"
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="passport_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="passport_scans/",
                verbose_name="Скан паспорта",
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="passport_number",
            field=models.CharField(
                default=1234567, max_length=20, verbose_name="Номер паспорта"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="passport_series",
            field=models.CharField(
                default="AA", max_length=10, verbose_name="Серия паспорта"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="pinfl",
            field=models.CharField(
                default="123456789",
                max_length=14,
                verbose_name="ЖШШИР (PINFL)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Telegram username"
            ),
        ),
    ]
