# Generated by Django 5.2 on 2025-08-01 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_courseregistration_telegram_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "company_name_uz",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "company_name_ru",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "company_name_en",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("logo", models.ImageField(upload_to="company_logos/")),
            ],
            options={
                "verbose_name": "Компания студента",
                "verbose_name_plural": "Компании студентов",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="ФИО"),
                ),
                (
                    "full_name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "full_name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "full_name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "job_title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "job_title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "job_title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                ("description", models.TextField(verbose_name="Отзыв")),
                (
                    "description_uz",
                    models.TextField(null=True, verbose_name="Отзыв"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Отзыв"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Отзыв"),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        upload_to="reviews/profile/", verbose_name="Фото"
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        upload_to="reviews/logos/",
                        verbose_name="Логотип компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
