# Generated by Django 5.2 on 2025-08-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_companystudent_review_company_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
