# Generated by Django 5.2 on 2025-12-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_delete_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на официальный сайт компании",
                verbose_name="Ссылка на сайт",
            ),
        ),
    ]
