# Generated by Django 5.2 on 2025-12-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("common", "0002_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="common.badge",
                verbose_name="Бейдж",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
