# Generated by Django 5.2 on 2025-08-02 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Заголовок"
                    ),
                ),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "content_uz",
                    models.TextField(null=True, verbose_name="Контент"),
                ),
                (
                    "content_ru",
                    models.TextField(null=True, verbose_name="Контент"),
                ),
                (
                    "content_en",
                    models.TextField(null=True, verbose_name="Контент"),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "location_name",
                    models.CharField(
                        max_length=255, verbose_name="Название локации"
                    ),
                ),
                (
                    "location_name_uz",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "location_name_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "location_name_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес"),
                ),
                (
                    "address_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "address_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка",
                "verbose_name_plural": "Настройки",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "logo",
                    models.ImageField(
                        upload_to="social/logos/", verbose_name="Логотип"
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="common.setting",
                        verbose_name="Настройка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
    ]
