# Generated by Django 5.2 on 2025-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="location_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание локации"
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="location_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание локации"
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="location_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание локации"
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="location_description_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание локации"
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
    ]
