# Generated by Django 5.2 on 2025-05-05 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="companies/", verbose_name="Логотип"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="HEX код цвета",
                        max_length=20,
                        verbose_name="Цвет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Сообщение"),
                ),
            ],
            options={
                "verbose_name": "Заявка на контакт",
                "verbose_name_plural": "Заявки на контакт",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория курса",
                "verbose_name_plural": "Категории курсов",
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="Биография"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="mentors/", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ментор",
                "verbose_name_plural": "Менторы",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/icons/",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "icon_type",
                    models.CharField(
                        blank=True,
                        help_text="Например: python, react, node",
                        max_length=50,
                        verbose_name="Тип иконки",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Новички"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        default="8-12 месяцев",
                        max_length=50,
                        verbose_name="Продолжительность",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, verbose_name="Рекомендуемый"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=False, verbose_name="Новый курс"
                    ),
                ),
                (
                    "what_will_learn",
                    models.TextField(
                        blank=True, verbose_name="Чему вы научитесь"
                    ),
                ),
                (
                    "video_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Часы видео"
                    ),
                ),
                (
                    "coding_exercises",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Упражнения по кодированию"
                    ),
                ),
                (
                    "articles",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Статьи"
                    ),
                ),
                (
                    "has_certificate",
                    models.BooleanField(
                        default=True, verbose_name="Сертификат"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.coursecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="CourseOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат обучения",
                "verbose_name_plural": "Результаты обучения",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Сообщение"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация на курс",
                "verbose_name_plural": "Регистрации на курсы",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="testimonials/", verbose_name="Аватар"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="courses.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="CourseCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_courses",
                        to="courses.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_companies",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания курса",
                "verbose_name_plural": "Компании курсов",
                "unique_together": {("course", "company")},
            },
        ),
        migrations.CreateModel(
            name="CourseMentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_mentors",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_courses",
                        to="courses.mentor",
                        verbose_name="Ментор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ментор курса",
                "verbose_name_plural": "Менторы курсов",
                "unique_together": {("course", "mentor")},
            },
        ),
    ]
