# Generated by Django 5.2 on 2025-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0002_course_description_ru_course_description_uz_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="message_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="message_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_ru",
            field=models.CharField(
                default="8-12 месяцев",
                max_length=50,
                null=True,
                verbose_name="Продолжительность",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_uz",
            field=models.CharField(
                default="8-12 месяцев",
                max_length=50,
                null=True,
                verbose_name="Продолжительность",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level_ru",
            field=models.CharField(
                choices=[
                    ("beginner", "Новички"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                default="beginner",
                max_length=20,
                null=True,
                verbose_name="Уровень",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level_uz",
            field=models.CharField(
                choices=[
                    ("beginner", "Новички"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                default="beginner",
                max_length=20,
                null=True,
                verbose_name="Уровень",
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="message_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="message_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="position_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="position_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Текст отзыва"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="text_uz",
            field=models.TextField(null=True, verbose_name="Текст отзыва"),
        ),
    ]
