# Generated by Django 5.2 on 2025-05-17 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_courseregistration_passport_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseregistration",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="WRONG_TELEGRAM_USERNAME",
                        message="Telegram username can contain letters, numbers, and underscores, optionally starting with '@'",
                        regex="^@?[\\w]+$",
                    )
                ],
                verbose_name="Telegram username",
            ),
        ),
    ]
