# Generated by Django 5.2 on 2025-12-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
