# Generated by Django 5.2 on 2025-12-12 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corporate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "description_uz",
                    models.TextField(null=True, verbose_name="Описание"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Описание"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Корпоратив",
                "verbose_name_plural": "Корпоративы",
            },
        ),
        migrations.CreateModel(
            name="ApplyCorporateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "cv",
                    models.FileField(
                        upload_to="corporate/cv/", verbose_name="Резюме (CV)"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Сообщение"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="corporations.corporate",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на корпоратив",
                "verbose_name_plural": "Заявки на корпоратив",
            },
        ),
        migrations.CreateModel(
            name="CorporateFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Особенность"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Особенность"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Особенность"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Особенность"
                    ),
                ),
                (
                    "corporate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="corporations.corporate",
                        verbose_name="Корпоратив",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность корпоратива",
                "verbose_name_plural": "Особенности корпоратива",
            },
        ),
    ]
