# Generated by Django 5.2 on 2025-08-02 17:26

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "job_title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "job_title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "job_title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="Слаг"
                    ),
                ),
                (
                    "salary",
                    models.CharField(max_length=255, verbose_name="Зарплата"),
                ),
                (
                    "salary_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Зарплата"
                    ),
                ),
                (
                    "salary_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Зарплата"
                    ),
                ),
                (
                    "salary_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Зарплата"
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        max_length=255, verbose_name="Опыт работы"
                    ),
                ),
                (
                    "experience_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Опыт работы"
                    ),
                ),
                (
                    "experience_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Опыт работы"
                    ),
                ),
                (
                    "experience_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Опыт работы"
                    ),
                ),
                (
                    "type_work",
                    models.CharField(
                        max_length=255, verbose_name="Тип занятости"
                    ),
                ),
                (
                    "type_work_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Тип занятости"
                    ),
                ),
                (
                    "type_work_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Тип занятости"
                    ),
                ),
                (
                    "type_work_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Тип занятости"
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        max_length=255, verbose_name="График работы"
                    ),
                ),
                (
                    "work_schedule_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="График работы"
                    ),
                ),
                (
                    "work_schedule_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="График работы"
                    ),
                ),
                (
                    "work_schedule_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="График работы"
                    ),
                ),
                (
                    "work_format",
                    models.CharField(
                        max_length=255, verbose_name="Формат работы"
                    ),
                ),
                (
                    "work_format_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Формат работы"
                    ),
                ),
                (
                    "work_format_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Формат работы"
                    ),
                ),
                (
                    "work_format_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Формат работы"
                    ),
                ),
                (
                    "responsibilities",
                    tinymce.models.HTMLField(verbose_name="Обязанности"),
                ),
                (
                    "responsibilities_uz",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Обязанности"
                    ),
                ),
                (
                    "responsibilities_ru",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Обязанности"
                    ),
                ),
                (
                    "responsibilities_en",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Обязанности"
                    ),
                ),
                (
                    "requirements",
                    tinymce.models.HTMLField(verbose_name="Требования"),
                ),
                (
                    "requirements_uz",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Требования"
                    ),
                ),
                (
                    "requirements_ru",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Требования"
                    ),
                ),
                (
                    "requirements_en",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Требования"
                    ),
                ),
                (
                    "advantages",
                    tinymce.models.HTMLField(verbose_name="Преимущества"),
                ),
                (
                    "advantages_uz",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Преимущества"
                    ),
                ),
                (
                    "advantages_ru",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Преимущества"
                    ),
                ),
                (
                    "advantages_en",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="Преимущества"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="ФИО"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Эл. почта",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        upload_to="vacancy/applications/",
                        verbose_name="Резюме (CV)",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Сопроводительное письмо",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="careers.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вакансию",
                "verbose_name_plural": "Заявки на вакансии",
            },
        ),
    ]
