# Generated by Django 5.2 on 2025-12-17 05:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="short_requirements",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                help_text="Максимум 5 пункта для отображения в списке вакансий",
                size=None,
                verbose_name="Требования (кратко для списка)",
            ),
        ),
    ]
