# Generated by Django 5.2 on 2025-12-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0002_vacancy_short_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="short_requirements",
        ),
        migrations.CreateModel(
            name="ShortRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Требование"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок отображения (меньше = выше)",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_requirements_list",
                        to="careers.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Краткое требование",
                "verbose_name_plural": "Краткие требования",
                "ordering": ["order", "id"],
            },
        ),
    ]
